language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
script:
  - cd src
  - python -m test.tester
after_success:
  - docker build -t zachzundel/sbolvalidator:snapshot .
  - docker/push.sh
