sudo: required

language: python
python:
  - "3.6"
services:
  - docker

jobs:
  include:
    - stage: test
      install: "pip install -r requirements.txt"
      script:
        - cd src
        - python -m test.tester
    - stage: push
      install: docker build -t zachzundel/sbolvalidator:snapshot .
      script: docker/push.sh
      if: branch = master AND type = push
