name: Deploy

on:
  push: 
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with: 
          python-version: '3.x'
      - run: |
          pip install -r requirements.txt
          cd src
          python -m test.tester

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker/build.sh
          docker/push.sh

  validator:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        name: Deploy container
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: systemctl restart validator
  
  converter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        name: Deploy convertor
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: systemctl restart converter
